#################
### AUTOSTART ###
#################
exec-once = xrdb -merge ~/.Xresources
exec-once = hyprctl setcursor Nordzy-cursors 24
exec-once = hyprpaper
exec-once = waybar
exec-once = swaync
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = xdg-desktop-portal-hyprland &
exec-once = xdg-desktop-portal &

# Apps
exec-once = [workspace 3 silent] youtube-music
exec-once = sh -c "hyprctl dispatch workspace 3; discord & sleep 5; hyprctl dispatch workspace 1"
exec-once = hyprctl dispatch workspace 1

# Theme
# for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

# for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface cursor-theme "Nordzy-cursors"
exec = gsettings set org.gnome.desktop.interface cursor-size 24
