# Minimalist Theme Settings

general {
    gaps_in = 1
    gaps_out = 2
    border_size = 1
    col.active_border = rgba(ffffffaa)
    col.inactive_border = rgba(333333aa)
    layout = dwindle
}

decoration {
    rounding = 0
    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

animations {
    enabled = yes
    bezier = sharp, 0, 0, 0, 1
    animation = windows, 1, 2, sharp, slide
    animation = workspaces, 1, 2, sharp, slide
}
